server:
  port: 8090
  
spring:
    application:
        name: product
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        ip-address: ${server.address:localhost}
