server:
  port: 8080
  
spring:
    application:
        name: gateway
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true
        ip-address: ${server.address:localhost}
zuul:
    ignoredServices: '*'
    set-content-length: true
    routes:
        productslist:
            path: /api/product/**/
            serviceId: product
            sensitiveHeaders:
            stripPrefix: false     